kumuluzee:
  name: priporocila_filmi
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PriporocilaDS
      connection-url: jdbc:postgresql://localhost:5432/priporocila
      username: postgres
      password: postgres
  dev:
    scan-libraries:
      - entitete
      - storitve


