kumuluzee:
  name: priporocila_filmi
  version: 1.0.0
  env:
    name: dev
  datasources:
    - jndi-name: jdbc/PriporocilaDS
      connection-url: jdbc:postgresql://localhost:5432/priporocila
      username: postgres
      password: postgres
  kumuluzee:
    openapi-mp:
      enabled: true
      servlet:
        mapping: /openapi-custom-mapping
      scan:
        packages: com.kumuluz.ee.samples.openapi
      servers: https://example-api.com,https://my-proxy.com
      ui:
        server-auto-config:
          enabled: true
          original-uri-check: false
    dev:
      scan-libraries:
        - entitete
        - storitve


